/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CampusFeedback {
  export type FeedbackStruct = {
    cid: string;
    contentHash: BytesLike;
    timestamp: BigNumberish;
  };

  export type FeedbackStructOutput = [
    cid: string,
    contentHash: string,
    timestamp: bigint
  ] & { cid: string; contentHash: string; timestamp: bigint };
}

export interface CampusFeedbackInterface extends Interface {
  getFunction(
    nameOrSignature: "getAllFeedback" | "getFeedbackCount" | "submitFeedback"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "FeedbackSubmitted"): EventFragment;

  encodeFunctionData(
    functionFragment: "getAllFeedback",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedbackCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitFeedback",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeedbackCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitFeedback",
    data: BytesLike
  ): Result;
}

export namespace FeedbackSubmittedEvent {
  export type InputTuple = [
    id: BigNumberish,
    cid: string,
    contentHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    cid: string,
    contentHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    cid: string;
    contentHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CampusFeedback extends BaseContract {
  connect(runner?: ContractRunner | null): CampusFeedback;
  waitForDeployment(): Promise<this>;

  interface: CampusFeedbackInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllFeedback: TypedContractMethod<
    [],
    [CampusFeedback.FeedbackStructOutput[]],
    "view"
  >;

  getFeedbackCount: TypedContractMethod<[], [bigint], "view">;

  submitFeedback: TypedContractMethod<
    [cid: string, contentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllFeedback"
  ): TypedContractMethod<[], [CampusFeedback.FeedbackStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getFeedbackCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitFeedback"
  ): TypedContractMethod<
    [cid: string, contentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FeedbackSubmitted"
  ): TypedContractEvent<
    FeedbackSubmittedEvent.InputTuple,
    FeedbackSubmittedEvent.OutputTuple,
    FeedbackSubmittedEvent.OutputObject
  >;

  filters: {
    "FeedbackSubmitted(uint256,string,bytes32,uint256)": TypedContractEvent<
      FeedbackSubmittedEvent.InputTuple,
      FeedbackSubmittedEvent.OutputTuple,
      FeedbackSubmittedEvent.OutputObject
    >;
    FeedbackSubmitted: TypedContractEvent<
      FeedbackSubmittedEvent.InputTuple,
      FeedbackSubmittedEvent.OutputTuple,
      FeedbackSubmittedEvent.OutputObject
    >;
  };
}
