/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CampusFeedback } from "./CampusFeedback";
export * as factories from "./factories";
export { CampusFeedback__factory } from "./factories/CampusFeedback__factory";
